; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Crysis Remastered Improvement Project"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Team MTL5"
#define MyAppURL "https://www.moddb.com/mods/improvement-project"
//#define InstallDataFolder "C:\\Crysis Remastered Improvement Project Build\\InstallData"

[Setup]
AppendDefaultDirName=no
AppId={{5825B7BF-803B-467A-9940-7323B6C9D508}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files (x86)\Steam\steamapps\common\Crysis Remastered
DefaultGroupName={#MyAppName}
DirExistsWarning=no
OutputBaseFilename=ImprovementProject {#MyAppVersion}
SolidCompression=yes
WizardStyle=modern
DisableProgramGroupPage=yes
InfoBeforeFile=readme_before.rtf


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "Main\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
//Remember that Warhead map data is stored in patch2, and overrides patch1 where applicable.
Source: "Patch\patch1.pak"; DestDir: "{app}\Patch"; Flags: ignoreversion
Source: "Patch\patch2.pak"; DestDir: "{app}\Patch"; Check: ShouldInstallWarhead; Flags: ignoreversion


//We copy the localization files regardless.
Source: "Patch\Localized\*"; DestDir: "{app}\Patch\Localized"; Flags: ignoreversion recursesubdirs createallsubdirs
//First we copy the main level data.

//We copy the new loadscreens and cfg files to override disabling of distant NPCs. These unfortunately must overwrite the OGs.
Source: "Optional\zzzz_UKAudio.pak"; DestDir: "{app}\Game"; Check: ShouldInstallAudio; Flags: ignoreversion
Source: "Optional\zzzz_UKWeapons.pak"; DestDir: "{app}\Game"; Check: ShouldInstallModels; Flags: ignoreversion
Source: "Optional\zzzz_C2StyleSuitFX.pak"; DestDir: "{app}\Game"; Check: ShouldInstallC2StyleSuitFX; Flags: ignoreversion
//Source: "Optional\zzzz_RevisedSuitFX.pak"; DestDir: "{app}\Game"; Check: ShouldInstallRevisedSuitFX; Flags: ignoreversion
Source: "Optional\zzz_Warhead.pak"; DestDir: "{app}\Game"; Check: ShouldInstallWarhead; Flags: ignoreversion

Source: "option1_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option1_full.png"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option2_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option2_full.wmv"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option3_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option3_full.png"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option4_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option4_full.png"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option5_c2_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option5_c2_full.png"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option5_classic_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
Source: "option5_classic_full.png"; DestDir: "{tmp}"; Flags: dontcopy
//Source: "option5_revised_small.bmp"; DestDir: "{tmp}"; Flags: dontcopy
//Source: "option5_revised_full.png"; DestDir: "{tmp}"; Flags: dontcopy

//Backup is special case.
Source: "Backup\*"; DestDir: "{app}\ImprovementProjectBackup"; Flags: ignoreversion recursesubdirs createallsubdirs uninsneveruninstall



[Code]
// Global variable declarations:
var
  FoundGameExePath: string;
  FoundInstallHint: string;
  GlobalDescriptionMemo: TMemo;
  OptionCheckBox1, OptionCheckBox2, OptionCheckBox3, OptionCheckBox4: TCheckBox;
  SuitHeader: TNewStaticText;
  rbSuitClassic, rbSuitModern: TRadioButton;
  SelectedSuitStyle: Integer;
  OptionLabel1, OptionLabel2, OptionLabel3, OptionLabel4: TLabel;
  CustomPage: TWizardPage;
  CurrentPreviewFullImage: string;
  //Installer variables.
  InstallAudio, InstallModels, InstallWarhead: Boolean;
  MaintenancePage: TWizardPage;
  rbModify, rbUninstall: TRadioButton;
  ForceClose: Boolean; // Global flag to force closure
  DetectionLabel: TNewStaticText;
  SuitDesc: TNewStaticText;
  
const
  faAnyFile = $3F;

  
  
// Returns S with a trailing '\' if it doesn't already have one.
function IncludeTrailingPathDelimiter(const S: string): string;
begin
  if (S <> '') and (S[Length(S)] <> '\') then
    Result := S + '\'
  else
    Result := S;
end;
  
// Alias for IncludeTrailingPathDelimiter.
function AddTrailingBackslash(const S: string): string;
begin
  Result := IncludeTrailingPathDelimiter(S);
end;

// Returns the position of SubStr in S starting at Offset.
function PosEx(const SubStr, S: string; Offset: Integer): Integer;
var
  P: Integer;
begin
  P := Pos(SubStr, Copy(S, Offset, Length(S) - Offset + 1));
  if P > 0 then
    Result := P + Offset - 1
  else
    Result := 0;
end;

// Splits an AnsiString into an array of strings using CR and LF as delimiters.
function SplitLines(const S: AnsiString): TArrayOfString;
var
  i, j, count: Integer;
begin
  count := 0;
  i := 1;
  while i <= Length(S) do
  begin
    j := i;
    while (j <= Length(S)) and not (S[j] in [#13, #10]) do
      Inc(j);
    SetArrayLength(Result, count + 1);
    Result[count] := Copy(S, i, j - i);
    Inc(count);
    while (j <= Length(S)) and (S[j] in [#13, #10]) do
      Inc(j);
    i := j;
  end;
end;

// Replaces all occurrences of OldPattern with NewPattern in S.
function ReplaceString(const S, OldPattern, NewPattern: string): string;
var
  i: Integer;
begin
  Result := S;
  i := Pos(OldPattern, Result);
  while i <> 0 do
  begin
    Delete(Result, i, Length(OldPattern));
    Insert(NewPattern, Result, i);
    i := Pos(OldPattern, Result);
  end;
end;
  
  // ------------------------------
  // Robust path helpers
  // ------------------------------
  function NormalizePath(const S: string): string;
  begin
    Result := Trim(S);
    Result := ReplaceString(Result, '\\', '\');
    // Steam sometimes stores forward slashes in some contexts; normalize if you want:
    Result := ReplaceString(Result, '/', '\');
    // Remove trailing slash
    if (Length(Result) > 0) and (Result[Length(Result)] = '\') then
      Delete(Result, Length(Result), 1);
  end;

  function ExtractFirstCommandToken(const Cmd: string): string;
  var
    S: string;
    p: Integer;
  begin
    S := Trim(Cmd);
    Result := '';

    if S = '' then Exit;

    if S[1] = '"' then
    begin
      p := PosEx('"', S, 2);
      if p > 0 then
        Result := Copy(S, 2, p - 2);
    end
    else
    begin
      p := Pos(' ', S);
      if p > 0 then
        Result := Copy(S, 1, p - 1)
      else
        Result := S;
    end;

    Result := Trim(Result);
  end;

  function MakeGameExePathFromRoot(const RootDir: string): string;
  begin
    Result := AddTrailingBackslash(NormalizePath(RootDir)) + 'Bin64\CrysisRemastered.exe';
  end;

  function TryGetSteamBasePath(var SteamPath: string): Boolean;
  begin
    SteamPath := '';

    // Most common
    if RegQueryStringValue(HKCU, 'Software\Valve\Steam', 'SteamPath', SteamPath) then
    begin
      SteamPath := NormalizePath(SteamPath);
      Result := (SteamPath <> '');
      Exit;
    end;

    // Sometimes present
    if RegQueryStringValue(HKCU, 'Software\Valve\Steam', 'InstallPath', SteamPath) then
    begin
      SteamPath := NormalizePath(SteamPath);
      Result := (SteamPath <> '');
      Exit;
    end;

    // Fallback: SteamExe -> derive directory
    if RegQueryStringValue(HKCU, 'Software\Valve\Steam', 'SteamExe', SteamPath) then
    begin
      SteamPath := ExtractFileDir(NormalizePath(SteamPath));
      Result := (SteamPath <> '');
      Exit;
    end;

    // Some systems may have it under HKLM (less common these days, but cheap to try)
    if RegQueryStringValue(HKLM, 'Software\Valve\Steam', 'InstallPath', SteamPath) then
    begin
      SteamPath := NormalizePath(SteamPath);
      Result := (SteamPath <> '');
      Exit;
    end;

    Result := False;
  end;

  // Parse a single VDF line for:  "path"  "X:\SteamLibrary"
  function TryParseVdfPathLine(const Line: string; var OutPath: string): Boolean;
  var
    k, p1, p2: Integer;
    S: string;
  begin
    Result := False;
    OutPath := '';

    S := Trim(Line);
    k := Pos('"path"', S);
    if k = 0 then Exit;

    // find first quote after "path"
    p1 := PosEx('"', S, k + 6); // 6 chars in "path"
    if p1 = 0 then Exit;

    p2 := PosEx('"', S, p1 + 1);
    if p2 = 0 then Exit;

    OutPath := Copy(S, p1 + 1, p2 - p1 - 1);
    OutPath := NormalizePath(OutPath);

    Result := (OutPath <> '');
  end;

  procedure AddUniquePath(var Arr: TArrayOfString; const P: string);
  var
    I: Integer;
  begin
    for I := 0 to GetArrayLength(Arr) - 1 do
      if CompareText(Arr[I], P) = 0 then Exit;

    SetArrayLength(Arr, GetArrayLength(Arr) + 1);
    Arr[GetArrayLength(Arr) - 1] := P;
  end;

  function TryFindExeInSteamLibraries(const SteamPath: string; var ExePath: string): Boolean;
  var
    LibFile: string;
    Vdf: AnsiString;
    Lines: TArrayOfString;
    I: Integer;
    LibRoot, Candidate: string;
    Libraries: TArrayOfString;
  begin
    Result := False;
    ExePath := '';

    // Always consider the main Steam folder as a "library root"
    SetArrayLength(Libraries, 0);
    AddUniquePath(Libraries, NormalizePath(SteamPath));

    LibFile := AddTrailingBackslash(SteamPath) + 'steamapps\libraryfolders.vdf';
    if LoadStringFromFile(LibFile, Vdf) then
    begin
      Lines := SplitLines(Vdf);
      for I := 0 to GetArrayLength(Lines) - 1 do
      begin
        if TryParseVdfPathLine(Lines[I], LibRoot) then
          AddUniquePath(Libraries, LibRoot);
      end;
    end;

    // Try each library root
    for I := 0 to GetArrayLength(Libraries) - 1 do
    begin
      Candidate := AddTrailingBackslash(Libraries[I]) +
                   'steamapps\common\Crysis Remastered\Bin64\CrysisRemastered.exe';

      if FileExists(Candidate) then
      begin
        ExePath := Candidate;
        Result := True;
        Exit;
      end;
    end;
  end;
  
  // ------------------------------
  // GOG detection
  // ------------------------------
  function ContainsTextCI(const Haystack, Needle: string): Boolean;
  begin
    Result := Pos(LowerCase(Needle), LowerCase(Haystack)) > 0;
  end;
  
  function TryFindExeInGOGGamesKey(const RootKey: Integer; const BaseKey: string; var ExePath: string): Boolean;
  var
    SubKeys: TArrayOfString;
    I: Integer;
    K, GameName, InstallPath: string;
    Candidate: string;
  begin
    Result := False;
    ExePath := '';

    if not RegGetSubkeyNames(RootKey, BaseKey, SubKeys) then Exit;

    for I := 0 to GetArrayLength(SubKeys) - 1 do
    begin
      K := BaseKey + '\' + SubKeys[I];

      GameName := '';
      // Value names vary; try common ones
      RegQueryStringValue(RootKey, K, 'gameName', GameName);
      if GameName = '' then RegQueryStringValue(RootKey, K, 'name', GameName);

      if (GameName <> '') and (not ContainsTextCI(GameName, 'Crysis Remastered')) then
         Continue;

      InstallPath := '';
      if RegQueryStringValue(RootKey, K, 'path', InstallPath) then
      begin
        InstallPath := NormalizePath(InstallPath);
        Candidate := MakeGameExePathFromRoot(InstallPath);
        if FileExists(Candidate) then
        begin
          ExePath := Candidate;
          Result := True;
          Exit;
        end;
      end;
    end;
  end;

  function TryFindExeViaUninstallEntries(const RootKey: Integer; const UninstallKey: string; var ExePath: string): Boolean;
  var
    SubKeys: TArrayOfString;
    I: Integer;
    K, Disp, InstallLoc, UninsStr, UninsExe, CandidateRoot, Candidate: string;
  begin
    Result := False;
    ExePath := '';

    if not RegGetSubkeyNames(RootKey, UninstallKey, SubKeys) then Exit;

    for I := 0 to GetArrayLength(SubKeys) - 1 do
    begin
      K := UninstallKey + '\' + SubKeys[I];

      Disp := '';
      if not RegQueryStringValue(RootKey, K, 'DisplayName', Disp) then
        Continue;

      if Pos('Crysis Remastered', Disp) = 0 then
        Continue;

      CandidateRoot := '';

      InstallLoc := '';
      if RegQueryStringValue(RootKey, K, 'InstallLocation', InstallLoc) then
        CandidateRoot := NormalizePath(InstallLoc);

      if CandidateRoot = '' then
      begin
        // Often reliable for GOG: points at ...\unins000.exe (or similar) inside the game folder
        UninsStr := '';
        if RegQueryStringValue(RootKey, K, 'UninstallString', UninsStr) then
        begin
          UninsExe := NormalizePath(ExtractFirstCommandToken(UninsStr));
          if UninsExe <> '' then
            CandidateRoot := ExtractFileDir(UninsExe);
        end;
      end;

      if CandidateRoot <> '' then
      begin
        Candidate := MakeGameExePathFromRoot(CandidateRoot);
        if FileExists(Candidate) then
        begin
          ExePath := Candidate;
          Result := True;
          Exit;
        end;
      end;
    end;
  end;

procedure ExitProcess(ExitCode: Integer);
  external 'ExitProcess@kernel32.dll stdcall';

function GameRootFromExePath(const ExePath: string): string;
begin
  // ...\Crysis Remastered\Bin64\CrysisRemastered.exe -> ...\Crysis Remastered
  Result := ExtractFileDir(ExtractFileDir(ExePath));
end;


function FixupInstallDir(const InstallDir: string): string;
var
  D: string;
begin
  D := NormalizePath(InstallDir);

  // If they selected ...\Bin64, promote to parent
  if CompareText(ExtractFileName(D), 'Bin64') = 0 then
    D := ExtractFileDir(D);

  Result := D;
end;

function ValidateInstallLocation(var InstallDir: string): Boolean;
var
  Fixed: string;
begin
  Fixed := FixupInstallDir(InstallDir);

  // If we fixed it, update the UI field so user sees it
  if CompareText(Fixed, NormalizePath(InstallDir)) <> 0 then
    InstallDir := Fixed;

  Result := FileExists(MakeGameExePathFromRoot(InstallDir));
end;

procedure RemoveOldFiles();
var
  OldFiles: array of string;
  i: Integer;
  FilePath: string;
begin
  // Define the list of files to remove.
  SetArrayLength(OldFiles, 10);
  OldFiles[0] := '{app}\Game\zzz_C2StyleSuitFX.pak';
  OldFiles[1] := '{app}\Game\zzzz_C2StyleSuitFX.pak';
  OldFiles[2] := '{app}\Game\zzz_RevisedSuitFX.pak';
  OldFiles[3] := '{app}\Game\zzzz_RevisedSuitFX.pak';
  OldFiles[4] := '{app}\Game\zzz_Warhead.pak';
  OldFiles[5] := '{app}\Game\zzz_UKWeapons.pak';
  OldFiles[6] := '{app}\Game\zzzz_UKWeapons.pak';
  OldFiles[7] := '{app}\Game\zzz_UKAudio.pak';
  OldFiles[8] := '{app}\Game\zzzz_UKAudio.pak';
  OldFiles[9] := '{app}\Patch\patch2.pak';
  //OldFiles[5] := '{app}\autoexec.cfg';
  // Add more file paths as needed by increasing the array size and assigning them.

  // Loop through each file and attempt to delete it.
  for i := 0 to GetArrayLength(OldFiles) - 1 do
  begin
    FilePath := ExpandConstant(OldFiles[i]);
    if FileExists(FilePath) then
      if not DeleteFile(FilePath) then
        MsgBox('Could not delete ' + FilePath, mbError, MB_OK);
  end;
end;

procedure WizardFormCloseQuery(Sender: TObject; var CanClose: Boolean);
begin
  // If ForceClose is set, bypass the "Setup is not complete" warning.
  if ForceClose then
    CanClose := True
  else
    // Otherwise, prompt the user or implement your standard check.
    CanClose := MsgBox('Setup is not complete. Are you sure you want to exit?',
                       mbConfirmation, MB_YESNO) = idYes;
end;

function DeleteDirectory(const Dir: String): Boolean;
var
  FindRec: TFindRec;
  s: String;
begin
  Result := True;
  if FindFirst(AddBackslash(Dir) + '*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          s := AddBackslash(Dir) + FindRec.Name;
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
          begin
            if not DeleteDirectory(s) then
              Result := False;
            if not RemoveDir(s) then
              Result := False;
          end
          else
          begin
            if not DeleteFile(s) then
              Result := False;
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

function DeleteExtractedPreviewFiles(): Boolean;
var
  I: Integer;
  FilesToDelete: array of string;
  P: string;
begin
  Result := True;

  // Only delete files we know *we* extracted into {tmp}.
  SetArrayLength(FilesToDelete, 12);
  FilesToDelete[0]  := 'option1_small.bmp';
  FilesToDelete[1]  := 'option1_full.png';
  FilesToDelete[2]  := 'option2_small.bmp';
  FilesToDelete[3]  := 'option2_full.wmv';
  FilesToDelete[4]  := 'option3_small.bmp';
  FilesToDelete[5]  := 'option3_full.png';
  FilesToDelete[6]  := 'option4_small.bmp';
  FilesToDelete[7]  := 'option4_full.png';
  FilesToDelete[8]  := 'option5_c2_small.bmp';
  FilesToDelete[9]  := 'option5_c2_full.png';
  FilesToDelete[10] := 'option5_classic_small.bmp';
  FilesToDelete[11] := 'option5_classic_full.png';

  for I := 0 to GetArrayLength(FilesToDelete) - 1 do
  begin
    P := ExpandConstant('{tmp}\') + FilesToDelete[I];

    //If it doesn't exist, that's fine.
    if FileExists(P) then
    begin
      //If locked/in use, just report failure and keep going.
      if not DeleteFile(P) then
        Result := False;
    end;
  end;
end;


procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    // Call our custom file removal function before the installer copies new files.
    // This is actually intended to remove old files from previous versions of the mod.
    RemoveOldFiles();
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ResultCode: Integer;
  MsgText: string;
begin
  Result := True;

  // --- Maintenance Page Check ---
  if (MaintenancePage <> nil) and (CurPageID = MaintenancePage.ID) then
  begin
    if rbUninstall.Checked then
    begin
      // Launch the uninstaller without waiting
      if ShellExec('open', WizardForm.DirEdit.Text + '\unins000.exe', '',
                   WizardForm.DirEdit.Text, SW_SHOWNORMAL, ewNoWait, ResultCode) then
      begin
        CurrentPreviewFullImage := '';
        WizardForm.WizardSmallBitmapImage.Bitmap := nil; //Just to be safe, clear the current images.
        // Delete the temporary files extracted during setup.
        if not DeleteExtractedPreviewFiles() then
          MsgBox('Failed to delete temporary files.', mbError, MB_OK);

        Sleep(100);
        ExitProcess(0);
      end
      else
      begin
        MsgBox('Failed to launch the uninstaller.', mbError, MB_OK);
        Result := False;
        Exit;
      end;
    end;
  end;

  // --- Custom Options Page Confirm ---
  if (CustomPage <> nil) and (CurPageID = CustomPage.ID) then
  begin
    // Build message dynamically from current selections
    MsgText := 'Installing the Improvement Project will apply the following:' + #13#10;

    // Always-on (edit if these are not always true)
    MsgText := MsgText + '• Blood is enabled' + #13#10;
    MsgText := MsgText + '• Borderless windowed mode is enabled' + #13#10;

  // Suit selection
  if SelectedSuitStyle = 0 then
  begin
    MsgText := MsgText + '• Classic nanosuit controls are enabled' + #13#10;
    MsgText := MsgText + '• Leaning is bound to Q and E' + #13#10;
  end
  else
  begin
    MsgText := MsgText + '• Modern nanosuit controls are enabled' + #13#10;
    MsgText := MsgText + '• Armor/Cloak are bound to Q and E' + #13#10;
  end;

    // Optional checkboxes (read directly from the UI so it can’t go stale)
    if (OptionCheckBox2 <> nil) and OptionCheckBox2.Checked then
      MsgText := MsgText + '• Crysis 2-style weapon audio will be installed' + #13#10;

    if (OptionCheckBox3 <> nil) and OptionCheckBox3.Checked then
      MsgText := MsgText + '• Alternate weapon models will be installed' + #13#10;

    if (OptionCheckBox4 <> nil) and OptionCheckBox4.Checked then
      MsgText := MsgText + '• Crysis Warhead assets will be installed' + #13#10;

    MsgText := MsgText + #13#10 +
      'Do you want to continue?';

    if MsgBox(MsgText, mbConfirmation, MB_YESNO) = idNo then
    begin
      Result := False;
      Exit;
    end;
  end;
  
  if CurPageID = wpSelectDir then
  begin
    MsgText := WizardForm.DirEdit.Text;
    if not ValidateInstallLocation(MsgText) then
    begin
      MsgBox(
        'Please select the Crysis Remastered *game folder* (the folder that contains "Bin64").' + #13#10 +
        'Example: ...\Crysis Remastered (not ...\Crysis Remastered\Bin64).',
        mbError, MB_OK);
      Result := False;
    end
    else
      WizardForm.DirEdit.Text := MsgText; // apply any fixup
  end;
end;

const
  mbYesNo = 4;          // Yes/No buttons
  mbIconQuestion = 32;  // Question icon

// Searches for the game executable and returns its *full path*.
// Order: DefaultDir -> Steam -> GOG (registry) -> Uninstall entries
function FindGameExecutablePath(DefaultDir: string): string;
var
  Candidate, SteamPath, Found: string;
begin
  Result := '';
  FoundInstallHint := 'No installation auto-detected.';

  // 1) DefaultDir (root)
  Candidate := MakeGameExePathFromRoot(DefaultDir);
  if FileExists(Candidate) then
  begin
    Result := Candidate;
    FoundInstallHint := 'Found install in default path.';
    Exit;
  end;

  // 2) Steam
  SteamPath := '';
  if TryGetSteamBasePath(SteamPath) then
  begin
    Found := '';
    if TryFindExeInSteamLibraries(SteamPath, Found) then
    begin
      Result := Found;
      FoundInstallHint := 'Found Steam install (Steam libraries).';
      Exit;
    end;
  end;

  // 3) GOG.com\Games keys (32/64)
  Found := '';
  if TryFindExeInGOGGamesKey(HKLM, 'SOFTWARE\WOW6432Node\GOG.com\Games', Found) then
  begin
    Result := Found;
    Exit;
  end;
  Found := '';
  if TryFindExeInGOGGamesKey(HKLM, 'SOFTWARE\GOG.com\Games', Found) then
  begin
    Result := Found;
    FoundInstallHint := 'Found GOG install (GOG.com registry key).';
    Exit;
  end;
  Found := '';
  if TryFindExeInGOGGamesKey(HKCU, 'SOFTWARE\GOG.com\Games', Found) then
  begin
    Result := Found;
    FoundInstallHint := 'Found GOG install (GOG.com registry key).';
    Exit;
  end;

  // 4) Uninstall entries (very effective for GOG)
  Found := '';
  if TryFindExeViaUninstallEntries(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall', Found) then
  begin
    Result := Found;
    FoundInstallHint := 'Found install via Uninstall registry entries.';
    Exit;
  end;
  Found := '';
  if TryFindExeViaUninstallEntries(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall', Found) then
  begin
    Result := Found;
    FoundInstallHint := 'Found install via Uninstall registry entries.';
    Exit;
  end;
  Found := '';
  if TryFindExeViaUninstallEntries(HKCU, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall', Found) then
  begin
    Result := Found;
    FoundInstallHint := 'Found install via Uninstall registry entries.';
    Exit;
  end;

  // Not found
  Result := '';
end;

procedure PreviewImageClick(Sender: TObject);
var
  ErrorCode: Integer;
begin
  // If a full-resolution image is set, open it with the default viewer.
  if CurrentPreviewFullImage <> '' then
    ShellExec('', CurrentPreviewFullImage, '', '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
end;

procedure UpdatePreview(const SmallImage, FullImage: string);
begin
  if SmallImage = '' then
  begin
    // Clear the preview image by setting the bitmap to nil (or an empty bitmap)
    WizardForm.WizardSmallBitmapImage.Bitmap := nil;
    CurrentPreviewFullImage := '';
  end
  else
  begin
    try
      WizardForm.WizardSmallBitmapImage.Bitmap.LoadFromFile(ExpandConstant('{tmp}\' + SmallImage));
      CurrentPreviewFullImage := ExpandConstant('{tmp}\' + FullImage);
    except
      CurrentPreviewFullImage := '';
    end;
  end;
end;

procedure SuitRadioClick(Sender: TObject);
begin
  if rbSuitClassic.Checked then
  begin
    SuitDesc.Caption :=
      'Classic: The original 2007 PC control scheme, offering greater control over Nanosuit. Strength / Speed / Armor / Cloak are selected manually on the suit wheel, and Q and E lean left/right.';
    SelectedSuitStyle := 0;
  end
  else if rbSuitModern.Checked then
  begin
  SuitDesc.Caption :=
    'Modern: Streamlined 2011-style controls. Q = Armor, E = Cloak, leaning is disabled, and Strength and Speed are contextual. Also updates nanosuit visuals, including a blue Armor glow.';
    SelectedSuitStyle := 1;
  end;
end;

function ShouldInstallAudio: Boolean;
begin
  Result := InstallAudio;  // global boolean set from your OptionClick handler
end;

function ShouldInstallModels: Boolean;
begin
  Result := InstallModels;  // global boolean set from your OptionClick handler
end;

function ShouldInstallWarhead: Boolean;
begin
  Result := InstallWarhead;  // global boolean set from your OptionClick handler
end;

function ShouldInstallC2StyleSuitFX: Boolean;
begin
  Result := (SelectedSuitStyle = 1);  // global boolean set from your OptionClick handler
end;


// --- End Helper Functions ---
//Special function to copy the backup files into the game during uninstallation.

function CopyDirectory(const SourceDir, TargetDir: string): Boolean;
var
  FindRec: TFindRec;
  SourcePath, TargetPath, Dir: string;
  Success: Boolean;
begin
  Success := True;
  // Ensure the target directory exists.
  ForceDirectories(TargetDir);
  
  // Make sure the source directory path ends with a backslash.
  Dir := AddTrailingBackslash(SourceDir);
  
  // Enumerate all files and subdirectories in the source directory.
  if FindFirst(Dir + '*', FindRec) then
  begin
    try
      repeat
        // Skip the current and parent directory entries.
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          // Check if the found entry is a directory.
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
          begin
            // Recursively copy the subdirectory.
            if not CopyDirectory(Dir + FindRec.Name,
               AddTrailingBackslash(TargetDir) + FindRec.Name) then
              Success := False;
          end
          else
          begin
            // Construct full source and target file paths.
            SourcePath := Dir + FindRec.Name;
            TargetPath := AddTrailingBackslash(TargetDir) + FindRec.Name;
            // Copy the file; the True flag forces overwriting.
            if not FileCopy(SourcePath, TargetPath, True) then
              Success := False;
          end;
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
  Result := Success;
end;

// Called before the wizard is created; used to locate the game executable.
function InitializeSetup(): Boolean;
var
  DefaultInstallDir: string;
begin
  DefaultInstallDir := 'C:\Program Files (x86)\Steam\steamapps\common\Crysis Remastered';

  // Store the EXE PATH as the single source of truth
  FoundGameExePath := FindGameExecutablePath(DefaultInstallDir);

  if FoundGameExePath = '' then
  begin
    MsgBox('Auto-detection of the Crysis Remastered installation failed. ' +
           'Please verify the installation directory on the next screen.',
           mbInformation, MB_OK);
  end;

  Result := True;
end;


procedure OptionClick(Sender: TObject);
begin
  if (Sender = OptionCheckBox1) or (Sender = OptionLabel1) then
  begin
    GlobalDescriptionMemo.Text :=
      'Baseline files for the mod. Bug fixes, optimizations, restored cut content.';
    UpdatePreview('option1_small.bmp', 'option1_full.png');
  end
  else if (Sender = OptionCheckBox2) or (Sender = OptionLabel2) then
  begin
    InstallAudio := OptionCheckBox2.Checked;
    GlobalDescriptionMemo.Text :=
      'Overhauled weapon audio originally developed for the Crysis console port from 2011, similar in style to Crysis 2. This audio is much better mixed than default remastered audio. Click the preview thumbnail to hear the difference.';
    UpdatePreview('option2_small.bmp', 'option2_full.wmv');
  end
    else if (Sender = OptionCheckBox3) or (Sender = OptionLabel3) then
  begin
    // Only toggle when the checkbox itself is clicked
    if (Sender = OptionCheckBox3) then
    begin
      InstallModels := OptionCheckBox3.Checked;

      // If Models turned on, force Warhead off
      if InstallModels then
      begin
        OptionCheckBox4.Checked := False;
        InstallWarhead := False;
      end;
    end;

    GlobalDescriptionMemo.Text :=
      'Uses redesigned weapon models for the SOCOM, Scar, and FY71 from 2011 console port. ' +
      'Note: cannot be installed together with Warhead assets.';
    UpdatePreview('option3_small.bmp', 'option3_full.png');
  end
  else if (Sender = OptionCheckBox4) or (Sender = OptionLabel4) then
  begin
    // Only toggle when the checkbox itself is clicked
    if (Sender = OptionCheckBox4) then
    begin
      InstallWarhead := OptionCheckBox4.Checked;

      // If Warhead turned on, force Models off
      if InstallWarhead then
      begin
        OptionCheckBox3.Checked := False;
        InstallModels := False;
      end;
    end;

  GlobalDescriptionMemo.Text :=
    'Adds selected Crysis Warhead weapons, vehicles, and Ceph variants.' + #13#10 + #13#10 +
    'Experimental. Does not include Warhead campaign, updated Ceph Trooper AI, or grenade launcher.' + #13#10 + #13#10 +
    'Incompatible with Alternate Weapon Models.';
    UpdatePreview('option4_small.bmp', 'option4_full.png');
  end
  else
    GlobalDescriptionMemo.Text := '';
    
end;

procedure PreExtractPreviewFiles();
begin
  // Pre-extract all preview files once.
  ExtractTemporaryFile('option1_small.bmp');
  ExtractTemporaryFile('option1_full.png');
  ExtractTemporaryFile('option2_small.bmp');
  ExtractTemporaryFile('option2_full.wmv');
  ExtractTemporaryFile('option3_small.bmp');
  ExtractTemporaryFile('option3_full.png');
  ExtractTemporaryFile('option4_small.bmp');
  ExtractTemporaryFile('option4_full.png');
  ExtractTemporaryFile('option5_c2_small.bmp');
  ExtractTemporaryFile('option5_c2_full.png');
  ExtractTemporaryFile('option5_classic_small.bmp');
  ExtractTemporaryFile('option5_classic_full.png');
end;


procedure RestoreAndRemoveBackup();
var
  BackupDir, AppDir: string;
begin
  BackupDir := ExpandConstant('{app}\ImprovementProjectBackup');
  AppDir := ExpandConstant('{app}');

  if not DirExists(BackupDir) then
  begin
    MsgBox('Backup folder not found: ' + BackupDir + #13#10 +
           'Cannot restore original files.', mbError, MB_OK);
    Exit;
  end;

  //Restore originals back into the game folder (overwrite allowed)
  if not CopyDirectory(BackupDir, AppDir) then
  begin
    MsgBox('Failed to restore original files from:' + #13#10 + BackupDir,
           mbError, MB_OK);
    Exit;
  end;

  //Remove the backup folder after restore
  //DelTree returns False if something was locked or couldn’t be removed.
  if not DelTree(BackupDir, True, True, True) then
  begin
    // Not fatal — the game is restored. But tell the user.
    MsgBox('Original files were restored, but the backup folder could not be removed:' + #13#10 +
           BackupDir + #13#10 +
           'You may delete it manually.', mbInformation, MB_OK);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    RestoreAndRemoveBackup();
  end;
end;

//Called after the wizard is created; updates UI and creates custom page.
procedure InitializeWizard();
var
  InstallDir, ModFilePath: string;
begin
  //WizardForm.CancelButton.OnClick := @CancelButtonClick;
  try
   //Extract the image to the temp directory.
    PreExtractPreviewFiles();
  except
    //Handle error if we can't write to tmp.
  end;
  
  //If we autodetected the EXE, set the install directory to the game ROOT derived from it.
  if FoundGameExePath <> '' then
    WizardForm.DirEdit.Text := GameRootFromExePath(FoundGameExePath);
  
  //Use the install directory from the registry (as shown in the directory edit field)
  InstallDir := WizardForm.DirEdit.Text;
  // Build the full path to the mod file.
  
  //Auto-detection label
  DetectionLabel := TNewStaticText.Create(WizardForm);
  DetectionLabel.Parent := WizardForm.DirEdit.Parent;

  DetectionLabel.Left := WizardForm.DirEdit.Left;
  DetectionLabel.Top := WizardForm.DirEdit.Top + WizardForm.DirEdit.Height + ScaleY(8);

  DetectionLabel.Width := WizardForm.DirEdit.Parent.ClientWidth - DetectionLabel.Left;
  DetectionLabel.Height := ScaleY(30);

  DetectionLabel.Caption := 'Auto-detection:'#13#10 + FoundInstallHint;
  
  //Note. We copy the entirety of Main into the folder, so zzz_ImprovementProject.pak will be present.
  ModFilePath := AddTrailingBackslash(InstallDir) + 'Game\zzz_ImprovementProject.pak';
  if FileExists(ModFilePath) then
  begin
    //A previous installation of the mod was found; create a maintenance page.
    MaintenancePage := CreateCustomPage(wpWelcome, 'Maintenance Options',
      'A previous installation of the mod was detected. Please choose an action:');

    rbModify := TRadioButton.Create(MaintenancePage.Surface);
    rbModify.Parent := MaintenancePage.Surface;
    rbModify.Left := ScaleX(0);
    rbModify.Top := ScaleY(8);

    // Make it wrap manually + give it room
    rbModify.Caption := 'Modify Installation'#13#10 + ' (Reinstall, Change Options, Upgrade from Previous Version)';
    rbModify.Width := MaintenancePage.SurfaceWidth - rbModify.Left;
    rbModify.Height := ScaleY(34);
    rbModify.Checked := True;

    rbUninstall := TRadioButton.Create(MaintenancePage.Surface);
    rbUninstall.Parent := MaintenancePage.Surface;
    rbUninstall.Left := ScaleX(0);
    rbUninstall.Top := rbModify.Top + rbModify.Height + ScaleY(6);
    rbUninstall.Caption := 'Uninstall';
    rbUninstall.Width := MaintenancePage.SurfaceWidth - rbUninstall.Left;
    rbUninstall.Height := ScaleY(18);

  end;

 
  //Create a custom page after the destination selection page.
  CustomPage := CreateCustomPage(wpSelectDir, 'Installation Options',
    'Select the extra options you wish to install. "Required files" is mandatory.');
    
  // Create the description memo on the custom page.
  GlobalDescriptionMemo := TMemo.Create(CustomPage.Surface);
  GlobalDescriptionMemo.Parent := CustomPage.Surface;
  GlobalDescriptionMemo.Left := ScaleX(300); //Was 2220
  GlobalDescriptionMemo.Top := ScaleY(10);
  GlobalDescriptionMemo.Width := ScaleX(200);
  GlobalDescriptionMemo.Height := ScaleY(150);
  GlobalDescriptionMemo.ReadOnly := True;
  GlobalDescriptionMemo.WordWrap := True;
  GlobalDescriptionMemo.Text := 'Click an option to see its description.';
  
  
  //Image
  // Reposition an existing image control and assign a bitmap to it.
  WizardForm.WizardSmallBitmapImage.Parent := CustomPage.Surface;
  WizardForm.WizardSmallBitmapImage.Left := GlobalDescriptionMemo.Left;
  WizardForm.WizardSmallBitmapImage.Top := GlobalDescriptionMemo.Top + GlobalDescriptionMemo.Height + ScaleY(10);
  WizardForm.WizardSmallBitmapImage.Width := ScaleX(100);
  WizardForm.WizardSmallBitmapImage.Height := ScaleY(100);
  WizardForm.WizardSmallBitmapImage.OnClick := @PreviewImageClick;
  WizardForm.WizardSmallBitmapImage.Cursor := crHand;
  

  // Option 1: Required files (mandatory)
  OptionCheckBox1 := TCheckBox.Create(CustomPage.Surface);
  OptionCheckBox1.Parent := CustomPage.Surface;
  OptionCheckBox1.Left := ScaleX(10);
  OptionCheckBox1.Top := ScaleY(10);
  OptionCheckBox1.Width := ScaleX(15);  // small area; caption is separate
  OptionCheckBox1.Checked := True;
  OptionCheckBox1.Enabled := False;  // user cannot change this option
  OptionCheckBox1.OnClick := @OptionClick;

  OptionLabel1 := TLabel.Create(CustomPage.Surface);
  OptionLabel1.Parent := CustomPage.Surface;
  OptionLabel1.Left := OptionCheckBox1.Left + OptionCheckBox1.Width + ScaleX(5);
  OptionLabel1.Top := OptionCheckBox1.Top;
  OptionLabel1.Caption := 'Required files';
  OptionLabel1.Cursor := crHand; // visually indicate clickable
  OptionLabel1.OnClick := @OptionClick;

  //Option 2: Crysis 2 Style Weapon Audio
  OptionCheckBox2 := TCheckBox.Create(CustomPage.Surface);
  OptionCheckBox2.Parent := CustomPage.Surface;
  OptionCheckBox2.Left := ScaleX(10);
  OptionCheckBox2.Top := ScaleY(35);
  OptionCheckBox2.Width := ScaleX(15);
  OptionCheckBox2.Checked := True;
  //We set checked to True and THEN we set the onClick handler.
  OptionCheckBox2.OnClick := @OptionClick;
  InstallAudio := True; //Make sure variable is set to true.


  OptionLabel2 := TLabel.Create(CustomPage.Surface);
  OptionLabel2.Parent := CustomPage.Surface;
  OptionLabel2.Left := OptionCheckBox2.Left + OptionCheckBox2.Width + ScaleX(5);
  OptionLabel2.Top := OptionCheckBox2.Top;
  OptionLabel2.Caption := 'Crysis 2 Style Weapon Audio (Recommended)';
  OptionLabel2.Cursor := crHand;
  OptionLabel2.OnClick := @OptionClick;

//Option 3: Alternate Weapon Models (PS3/360)
  OptionCheckBox3 := TCheckBox.Create(CustomPage.Surface);
  OptionCheckBox3.Parent := CustomPage.Surface;
  OptionCheckBox3.Left := ScaleX(10);
  OptionCheckBox3.Top := ScaleY(60);
  OptionCheckBox3.Width := ScaleX(15);
  OptionCheckBox3.OnClick := @OptionClick;

  OptionLabel3 := TLabel.Create(CustomPage.Surface);
  OptionLabel3.Parent := CustomPage.Surface;
  OptionLabel3.Left := OptionCheckBox3.Left + OptionCheckBox3.Width + ScaleX(5);
  OptionLabel3.Top := OptionCheckBox3.Top;
  OptionLabel3.Caption := 'Alternate Weapon Models';
  OptionLabel3.Cursor := crHand;
  OptionLabel3.OnClick := @OptionClick;
  
  //Option 4: Add Crysis Warhead Assets
  OptionCheckBox4 := TCheckBox.Create(CustomPage.Surface);
  OptionCheckBox4.Parent := CustomPage.Surface;
  OptionCheckBox4.Left := ScaleX(10);
  OptionCheckBox4.Top := ScaleY(85);
  OptionCheckBox4.Width := ScaleX(15);
  OptionCheckBox4.OnClick := @OptionClick;

  OptionLabel4 := TLabel.Create(CustomPage.Surface);
  OptionLabel4.Parent := CustomPage.Surface;
  OptionLabel4.Left := OptionCheckBox4.Left + OptionCheckBox4.Width + ScaleX(5);
  OptionLabel4.Top := OptionCheckBox4.Top;
  OptionLabel4.Caption := 'Crysis Warhead Assets (Experimental)';
  OptionLabel4.Cursor := crHand;
  OptionLabel4.OnClick := @OptionClick;
  
  // --- Nanosuit Version subsection ---
  SuitHeader := TNewStaticText.Create(WizardForm);
  SuitHeader.Parent := CustomPage.Surface;
  SuitHeader.Left := ScaleX(10);
  SuitHeader.Top := ScaleY(110);
  SuitHeader.Caption := 'Nanosuit Version';

  rbSuitClassic := TRadioButton.Create(WizardForm);
  rbSuitClassic.Parent := CustomPage.Surface;
  rbSuitClassic.Left := ScaleX(24);                 // indent under header
  rbSuitClassic.Top := SuitHeader.Top + ScaleY(18);
  rbSuitClassic.Caption := 'Classic';
  rbSuitClassic.OnClick := @SuitRadioClick;

  rbSuitModern := TRadioButton.Create(WizardForm);
  rbSuitModern.Parent := CustomPage.Surface;
  rbSuitModern.Left := ScaleX(24);
  rbSuitModern.Top := rbSuitClassic.Top + ScaleY(18);
  rbSuitModern.Caption := 'Modern';
  rbSuitModern.OnClick := @SuitRadioClick;
  
  SuitDesc := TNewStaticText.Create(WizardForm);
  SuitDesc.Parent := CustomPage.Surface;
  //SuitDesc.Left := ScaleX(24);
  SuitDesc.Top := rbSuitModern.Top + ScaleY(22);
  SuitDesc.Width := ScaleX(260);     // adjust to taste
  SuitDesc.Height := ScaleY(64);     // give room for wrapping
  SuitDesc.AutoSize := False;
  SuitDesc.WordWrap := True;
  SuitDesc.Caption := '';

  // Default selection + initialize preview/description
  rbSuitClassic.Checked := True;
  SelectedSuitStyle := 0;
  SuitRadioClick(rbSuitClassic);
  
  //Clear the preview image.
  UpdatePreview('', '');
  
end;
